#base "../../user/custom/resource/ui/hudplayerhealth.res"
#base "../../customizations/selected_customizations/xyz_ColorHealthCross.res"
#base "../../customizations/selected_customizations/xyz_HealthCross.res"
#base "../../customfiles/resource/ui/hudplayerhealth.res"
#base "../../basefiles/resource/ui/hudplayerhealth.res"